branches:
  - name: main
    channel: latest
  - name: "+([0-9])?(.{+([0-9]),x}).x"
    channel: latest
  - name: homol
    channel: frontend-homol
    prerelease: frontend-homol
  - name: dev
    channel: frontend-dev
    prerelease: frontend-dev

tagFormat: "v${version}"
ci: true

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: docs
          release: false
        - type: style
          release: false
        - type: test
          release: false
        - type: chore
          release: false
        - type: build
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: refactor
            section: Refactor
          - type: perf
            section: Performance
          - type: build
            section: Build
          - type: ci
            section: CI
          - type: chore
            section: Chore
          - type: docs
            section: Docs
          - type: test
            section: Tests
      writerOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
        commitsSort:
          - type
          - scope
          - subject
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - pnpm-lock.yaml
        - yarn.lock
        - package-lock.json
      message: |
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - "@semantic-release/github"
